module.exports = {
  AirPurifier: {
    name: '空气净化器',
    categoryKey: 'Airpurifier',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveRoadHub: {
    categoryKey: 'FiveRoadHub',
    name: '五路排插',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveRoadLight: {
    name: '五路灯',
    categoryKey: 'FiveRoadLight',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Locator: {
    categoryKey: 'Locator',
    name: '定位器',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Socket: {
    categoryKey: 'Socket',
    name: '插座',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  MultiSwitch: {
    name: '多路开关',
    categoryKey: 'Switchpanel',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  VideoCamera: {
    name: '摄像机',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Fan: {
    name: '风扇',
    categoryKey: 'Fan',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  RuYingMultiSwitch: {
    name: '如影多功能面板',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WisdomControl: {
    name: '智能控制板',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  KugouMusic: {
    name: '酷狗音乐',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricFan: {
    name: '电风扇',
    categoryKey: 'Fan',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WhiteLamp: {
    name: '白光灯',
    categoryKey: 'WhiteLamp',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AirConditioner: {
    name: '空调',
    categoryKey: 'AirConditioning',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AirCleaner: {
    name: '空气净化器',
    categoryKey: 'Airpurifier',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  BloodPressureMeter: {
    name: '血压计',
    categoryKey: 'BloodPressure',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  BodyScales: {
    name: '体脂秤',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  BodySensor: {
    name: '身体传感器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  DisinfectionCabinet: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricCurtains: {
    categoryKey: 'ElectricCurtains',
    name: '电动窗帘',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FivePlug: {
    name: '五孔单插',
    categoryKey: 'FivePlug',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveStreetlights: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FourStreetlights: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveSwitch: {
    name: '五路开关',
    categoryKey: 'FiveRoadSwith',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FourSwitch: {
    name: '四路开关',
    categoryKey: 'FourRoadSwith',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ThreeSwitch: {
    name: '三路开关',
    categoryKey: 'ThreeRoadSwitch',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  TwoSwitch: {
    name: '二路开关',
    categoryKey: 'TwoRoadSwitch',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  InsertKeyPower: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  IntelligentGateway: {
    name: '智能网关',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  OneLamp: {
    name: '一路灯',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  LaundryRack: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  MultifunctionAlarmHost: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  NewFan: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Router: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ThreePlug: {
    name: '三孔单插',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WallPlug: {
    name: '墙壁插头',
    categoryKey: 'USB-wall-plug',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ThreeStreetlights: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WaterHeater: {
    categoryKey: 'IntelligentWaterHeater',
    name: '热水器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WaterPurifier: {
    categoryKey: 'Waterpurifier',
    name: '净水器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AudibleVisualAlarm: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  EmergencyButton: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricOven: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  GasAlarm: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Heater: {
    categoryKey: 'Heater',
    name: '取暖器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Humidifier: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ImmersionSensor: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  MagneticDoor: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  PetFeedingDevice: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SmartRope: {
    categoryKey: 'Smart_rope',
    name: '智能跳绳',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SmokeAlarm: {
    categoryKey: 'FireGasAlert',
    name: '烟雾报警器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchOne: {
    categoryKey: 'OneRoadSwitch',
    name: '一路开关',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  TemperatureHumiditySensor: {
    name: '温湿传感器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Thermostat: {
    name: '温控器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  DimmerSwitch: {
    categoryKey: 'dimmer-switch',
    name: '调光开关',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricityStatsReceptacle: {
    categoryKey: 'electricitystatsreceptacle',
    name: '电量统计插座',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AromatherapyMachine: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricCar: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricCarV2: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-normal', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Switch: {
    categoryName: '开关面板',
    categoryKey: 'SwitchPanel',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchOneV2: {
    categoryName: '一路开关',
    categoryKey: 'SwitchOne',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchTwoV2: {
    categoryName: '二路开关',
    categoryKey: 'SwitchTwo',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchThreeV2: {
    categoryName: '三路开关',
    categoryKey: 'SwitchThree',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchFourV2: {
    categoryName: '四路开关',
    categoryKey: 'SwitchFour',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchFiveV2: {
    categoryName: '五路开关',
    categoryKey: 'SwitchFive',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WhiteLampV2: {
    name: '白光灯v2',
    categoryKey: 'WhiteLamp',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-normal', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  // --------------------two-----product-------------------------------
  GasAlarmTwo: {
    name: '燃气感应器',
    categoryKey: 'GasAlarmTwo',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  MagneticDoorTwo: {
    name: '门磁感应器',
    categoryKey: 'MagneticDoor',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  BodySensorsTwo: {
    name: '身体传感器v2',
    categoryKey: 'BodySensors',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SmokeAlarmTwo: {
    name: '烟雾报警器v2',
    categoryKey: 'FireGasAlert',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SwitchTwo: {
    name: '一二三键开关v2',
    categoryKey: 'Switch',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true, entry: 'app.tsx' }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
      ['panel-brunet', { enable: true, entry: 'app.tsx' }],
      ['panel-fresh', { enable: true, entry: 'app.tsx' }],
      ['panel-house', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchOneTwo: {
    name: '一键开关V2',
    categoryKey: 'SwitchOne',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true, entry: 'app.tsx' }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
      ['panel-brunet', { enable: true, entry: 'app.tsx' }],
      ['panel-fresh', { enable: true, entry: 'app.tsx' }],
      ['panel-house', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchTwoTwo: {
    name: '一键开关V2',
    categoryKey: 'SwitchTwo',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true, entry: 'app.tsx' }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
      ['panel-brunet', { enable: true, entry: 'app.tsx' }],
      ['panel-fresh', { enable: true, entry: 'app.tsx' }],
      ['panel-house', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchThreeTwo: {
    name: '三键路开关V2',
    categoryKey: 'SwitchThree',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true, entry: 'app.tsx' }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
      ['panel-brunet', { enable: true, entry: 'app.tsx' }],
      ['panel-fresh', { enable: true, entry: 'app.tsx' }],
      ['panel-house', { enable: true, entry: 'app.tsx' }],
    ],
  },

  HeaterTwo: {
    name: '取暖器v2',
    categoryKey: 'Heater',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SmartLocksTwo: {
    name: '智能门锁',
    categoryKey: 'VisualLock',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
      // ['panel-brunet', { enable: true, entry: 'app.tsx' }],
      // ['panel-fresh', { enable: true, entry: 'app.tsx' }],
      // ['panel-house', { enable: true, entry: 'app.tsx' }],
    ],
  },
  PeepHole: {
    name: '猫眼门锁',
    categoryKey: 'PeepholeLock',
    enable: true,
    viewportWidth: 375,
    panels: [
      // ['panel-cold', { enable: true }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WhiteLampTwo: {
    name: '冷暖灯',
    categoryKey: 'WhiteLamp',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  AirConditionerTwo: {
    name: '空调v2',
    categoryKey: 'AirConditioning',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  PetFeedingDeviceTwo: {
    name: '宠物喂食器v2',
    categoryKey: 'PetFeedingDevice',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  HumidifierTwo: {
    name: '加湿器',
    categoryKey: 'Humidifier',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  IntelligentGatewayTwo: {
    name: '网关',
    categoryKey: 'IntelligentGateway',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  ElectricCurtainsTwo: {
    name: '窗帘电机v2',
    categoryKey: 'ElectricCurtains',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  LaundryRackTwo: {
    name: '智能晾衣架v2',
    categoryKey: 'LaundryRack',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  DownLightTwo: {
    name: '筒灯',
    categoryKey: 'DownLight',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SpotlightsTwo: {
    name: '聚光灯',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  LightStripTwo: {
    name: '灯带',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
};
