module.exports = {
  AirPurifier: {
    name: '空调',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveRoadHub: {
    name: '五路集成器',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveRoadLight: {
    name: '五路灯',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Locator: {
    name: '定位器',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Socket: {
    name: '插座',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  MultiSwitch: {
    name: '多路开关',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  VideoCamera: {
    name: '摄像机',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Fan: {
    name: '风扇',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  RuyingMultiSwitch: {
    name: '如影多功能面板',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WisdomControl: {
    name: '智能控制板',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  KugouMusic: {
    name: '酷狗音乐',
    enable: true,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricFan: {
    name: '电风扇',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WhiteLamp: {
    name: '白光灯',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AirConditioner: {
    name: '空调',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AirCleaner: {
    name: '空气净化器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  BloodPressureMeter: {
    name: '血压计',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  BodyScales: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  BodySensor: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  DisinfectionCabinet: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricCurtains: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FivePlug: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveStreetlights: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FourStreetlights: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FiveSwitch: {
    name: '五路灯',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  FourSwitch: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ThreeSwitch: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  TwoSwitch: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  InsertKeyPower: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  IntelligentGateway: {
    name: '智能网关',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  OneLamp: {
    name: '一路灯',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  LaundryRack: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  MultifunctionAlarmHost: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  NewFan: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Router: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ThreePlug: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WallPlug: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ThreeStreetlights: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WaterHeater: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WaterPurifier: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AudibleVisualAlarm: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  EmergencyButton: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricOven: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  GasAlarm: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Heater: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Humidifier: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ImmersionSensor: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  MagneticDoor: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  PetFeedingDevice: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SmartRope: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SmokeAlarm: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  SwitchOne: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  TemperatureHumiditySensor: {
    name: '温湿传感器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Thermostat: {
    name: '温控器',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  DimmerSwitch: {
    name: '调光开关',
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricityStatsReceptacle: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  AromatherapyMachine: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricCar: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-default', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  ElectricCarV2: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-normal', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  Switch: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-normal', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WhiteLampV2: {
    enable: true,
    viewportWidth: 1125,
    panels: [
      ['panel-normal', { enable: true, entry: 'app.tsx' }],
      ['panel-dark', { enable: true, entry: 'app.tsx' }],
      ['panel-colorful', { enable: true, entry: 'app.tsx' }],
      ['panel-blueWhite', { enable: true, entry: 'app.tsx' }],
      ['panel-morandi', { enable: true, entry: 'app.tsx' }],
    ],
  },
  // --------------------two-----product-------------------------------
  GasAlarmTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  MagneticDoorTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  BodySensorsTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SmokeAlarmTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SwitchTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true, entry: 'app.tsx' }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
      ['panel-brunet', { enable: true, entry: 'app.tsx' }],
      ['panel-fresh', { enable: true, entry: 'app.tsx' }],
      ['panel-house', { enable: true, entry: 'app.tsx' }],
    ],
  },
  HeaterTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SmartLocksTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true, entry: 'app.tsx' }],
      // ['panel-brunet', { enable: true, entry: 'app.tsx' }],
      // ['panel-fresh', { enable: true, entry: 'app.tsx' }],
      // ['panel-house', { enable: true, entry: 'app.tsx' }],
    ],
  },
  WhiteLampTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  AirConditionerTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  PetFeedingDeviceTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  HumidifierTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  IntelligentGatewayTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  ElectricCurtainsTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  LaundryRackTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  DownLightTwo: {
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  SpotlightsTwo: {
    name: '聚光灯',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
  LightStripTwo: {
    name: '灯带',
    enable: true,
    viewportWidth: 375,
    panels: [
      ['panel-cold', { enable: true }],
      ['panel-card', { enable: true }],
      ['panel-brunet', { enable: true }],
      ['panel-fresh', { enable: true }],
      ['panel-house', { enable: true }],
    ],
  },
};
