// Generated by gulp icon - do not modify manually

import * as React from 'react';

const iconList = [
  'add',
  'gear',
  'more',
  'power',
  'reduce',
  'temp_unit_convert',
  'ultrasound'
];

export interface IconProps {
  color?: string;
  className?: string;
  height?: number;
  kind?: string | any;
  onClick?: () => void;
  preview?: boolean;
  size?: number;
  style?: any;
  width?: number;
  wrapperStyle?: any;
}
export default class IconCommon extends React.Component<IconProps, {}> {
  static defaultProps = {
    className: '',
    color: 'currentColor',
    size: 32
  };

  render() {
    const { kind, preview } = this.props;
    return preview ? this.renderPreview() : this.renderIcon(kind);
  }

  renderPreview() {
    return <div>{iconList.map(kind => this.renderPreviewKind(kind))}</div>;
  }

  renderIcon(kind: string) {
    const { wrapperStyle } = this.props;
    if (wrapperStyle) {
      return <div style={wrapperStyle}>{this.getIcon(kind)}</div>;
    }
    return this.getIcon(kind);
  }

  renderPreviewKind(kind: string) {
    return (
      <div key={kind}>
        <h3>&lt;Icon kind="{kind}" /&gt;</h3>
        {this.renderIcon(kind)}
      </div>
    );
  }

  getIcon(kind: string) {
    const { color, height, onClick, size, style, width, className } =
      this.props;

    switch (kind) {
      case 'add':
        return (
          <svg
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 80 80"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>编组 7</title>
            <g>
              <rect y="32" width="80" height="16" rx="8" />
              <rect
                transform="rotate(-90 40 40)"
                y="32"
                width="80"
                height="16"
                rx="8"
              />
            </g>
          </svg>
        );
      case 'gear':
        return (
          <svg
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 78 78"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>档位</title>
            <path d="M41.817 29.77C43.305 24.15 46.808 16.5 52.6 11.982c4.33-3.387 5.413-6.896 1.865-9.083C49.856.068 35.627-2.803 25.861 5.32c-1.155.967-2.792 4.103-1.898 8.09.793 3.58 4.33 12.047 9.593 17.416 2.199 2.22 6.995 3.614 8.261-1.055zm-12.05 6.424c-5.629-1.51-13.268-5.013-17.787-10.793-3.409-4.33-6.9-5.418-9.088-1.854-2.832 4.591-5.69 18.826 2.443 28.58.954 1.15 4.091 2.793 8.077 1.922 3.587-.827 12.059-4.33 17.41-9.616 2.221-2.199 3.62-6.995-1.054-8.233v-.006zm6.433 12.04c-1.5 5.612-5.002 13.25-10.787 17.79-4.347 3.41-5.424 6.89-1.877 9.099 4.608 2.803 18.843 5.679 28.603-2.443 1.149-.949 2.787-4.124 1.904-8.076-.805-3.609-4.33-12.068-9.588-17.42-2.198-2.22-7.012-3.635-8.255 1.05zm12.02-5.686c5.642 1.527 13.259 5.041 17.789 10.81 3.42 4.335 6.901 5.423 9.088 1.865 2.832-4.603 5.713-18.854-2.426-28.603-.982-1.149-4.097-2.787-8.089-1.893-3.597.805-12.058 4.32-17.405 9.605-2.21 2.182-3.625 6.99 1.044 8.216z" />
          </svg>
        );
      case 'more':
        return (
          <svg
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 74 74"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>更多</title>
            <g>
              <rect width="34" height="34" rx="8" />
              <rect x="40" width="34" height="34" rx="8" />
              <rect x="40" y="40" width="34" height="34" rx="8" />
              <rect y="40" width="34" height="34" rx="8" />
            </g>
          </svg>
        );
      case 'power':
        return (
          <svg
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 326 328"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>总开关</title>
            <g transform="translate(115 111)">
              <path d="M69.372 14.69a5.731 5.731 0 0 0 1.853 4.3c12.387 11.223 15.692 29.624 8.012 44.607S54.87 86.289 38.783 82.285C22.696 78.28 11.35 63.593 11.28 46.68c-.016-10.526 4.4-20.55 12.124-27.519a6.257 6.257 0 0 0 1.852-4.471c-.185-1.944-1.335-3.654-3.046-4.528a5.455 5.455 0 0 0-5.373.228C6.193 19.454.027 32.87 0 47.025c.176 13 5.437 25.388 14.61 34.402 9.173 9.014 21.495 13.905 34.22 13.582 19.367-.702 36.372-13.356 42.965-31.97 6.593-18.613 1.45-39.45-12.993-52.648a5.63 5.63 0 0 0-6.04-.883c-2.012.917-3.33 2.933-3.39 5.183z" />
              <rect x="41" width="12.246" height="58.859" rx="6.123" />
            </g>
          </svg>
        );
      case 'reduce':
        return (
          <svg
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 80 16"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>矩形备份</title>
            <rect
              x="60"
              y="92"
              width="80"
              height="16"
              rx="8"
              transform="translate(-60 -92)"
            />
          </svg>
        );
      case 'temp_unit_convert':
        return (
          <svg
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 66 57"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>温标切换</title>
            <g transform="translate(-1 -1.469)">
              <rect x="1" y="51" width="66" height="7" rx="3.5" />
              <rect
                transform="matrix(-1 0 0 1 68 0)"
                x="1"
                y="13"
                width="66"
                height="7"
                rx="3.5"
              />
              <rect
                transform="rotate(-30 14 48.5)"
                y="45"
                width="28"
                height="7"
                rx="3.5"
              />
              <rect
                transform="scale(-1 1) rotate(-30 0 208.299)"
                x="39"
                y="7"
                width="28"
                height="7"
                rx="3.5"
              />
            </g>
          </svg>
        );
      case 'ultrasound':
        return (
          <svg
            fill={color}
            height={height || size}
            width={width || size}
            onClick={onClick}
            style={style}
            className={className}
            viewBox="0 0 84 84"
            xmlns="http://www.w3.org/2000/svg"
          >
            <title>超声波</title>
            <path d="M41.996 84c-2.29 0-3.822-1.529-3.822-3.822V3.822C38.174 1.529 39.707 0 41.996 0s3.822 1.529 3.822 3.822v76.356c0 2.293-1.533 3.822-3.822 3.822zm19.089-15.271c-2.29 0-3.818-1.529-3.818-3.822V19.093c0-2.289 1.529-3.818 3.822-3.818 2.289 0 3.818 1.53 3.818 3.822v45.818c0 2.29-1.529 3.818-3.822 3.818v-.004zM3.818 57.27C1.528 57.271 0 55.747 0 53.453V30.547c0-2.294 1.529-3.822 3.822-3.822 2.289 0 3.814 1.528 3.814 3.822v22.906c0 2.294-1.525 3.822-3.818 3.822v-.004zm76.364 0c-2.293 0-3.822-1.524-3.822-3.818V30.547c0-2.294 1.529-3.822 3.822-3.822 2.29 0 3.818 1.528 3.818 3.822v22.906c0 2.294-1.529 3.822-3.822 3.822l.004-.004zM22.907 68.73c-2.293 0-3.822-1.529-3.822-3.822V19.093c0-2.289 1.529-3.818 3.822-3.818 2.289 0 3.818 1.53 3.818 3.822v45.818c0 2.29-1.53 3.818-3.822 3.818l.004-.004z" />
          </svg>
        );
      default:
        return null;
    }
  }
}
